"use client";

import { useState } from "react";

interface ApprovalsListProps {
  theme: string;
}

export function ApprovalsList({ theme }: ApprovalsListProps) {
  const v = (n: string) => `var(--${n})`;
  
  const IN = { p: 'in', pBg: '#0a66c2', pFg: '#fff' };
  const X = { p: 'X', pBg: theme === 'light' ? '#17202f' : '#e8edf6', pFg: theme === 'light' ? '#fff' : '#0a0e16' };
  const pf = (k: string) => k === 'in' ? IN : X;

  const initialItems = [
    {
      ...pf('in'), title: 'Why approval gates matter in AI publishing', meta: 'Generated by copywriter-v2 · draft #418 · 34m ago', q: '8.7 / 10', when: 'Today 1:30 PM',
      body: 'Your content team isn\u2019t slow \u2014 your approval loop is.\n\nWe let AI draft every post, but nothing ships without a human gate. Here\u2019s why that one rule saved us twice last month:\n\n\u2192 A stat that was 3 years stale\n\u2192 A claim our lawyers would have hated\n\nAutomation writes. Humans decide. That\u2019s the whole system.',
      scores: [
        { k: 'Hook', v: '9.1', pct: 91, c: v('grn') }, { k: 'Clarity', v: '8.8', pct: 88, c: v('grn') }, { k: 'Accuracy', v: '8.5', pct: 85, c: v('grn') }, { k: 'Brand fit', v: '8.2', pct: 82, c: v('grn') },
      ],
      checks: [
        { m: '✓', c: v('grn'), t: '3 statistics verified against sources' }, { m: '✓', c: v('grn'), t: 'No unverifiable claims detected' }, { m: '✓', c: v('grn'), t: 'Tone matches brand guide v3' },
      ],
      srcN: 6, sources: ['HBR', 'a16z blog', 'HN #41283', 'Lenny\u2019s', 'X thread', 'YC library'],
    },
    {
      ...pf('X'), title: 'LinkedIn content systems for B2B startups', meta: 'Generated by copywriter-v2 · draft #421 · 12m ago', q: '7.9 / 10', when: 'Tomorrow 9:15 AM',
      body: 'Most B2B founders post randomly and call it a strategy.\n\nA content system beats inspiration. The 5-step loop we run: (thread)\n\n1. Listen \u2014 mine replies, reviews, support tickets\n2. Score \u2014 rank topics by audience pull\n3. Draft \u2014 AI writes, humans gate\n4. Schedule \u2014 3 slots a day, every day\n5. Measure \u2014 kill what doesn\u2019t move followers',
      scores: [
        { k: 'Hook', v: '8.4', pct: 84, c: v('grn') }, { k: 'Clarity', v: '8.0', pct: 80, c: v('grn') }, { k: 'Accuracy', v: '7.1', pct: 71, c: v('amb') }, { k: 'Brand fit', v: '8.1', pct: 81, c: v('grn') },
      ],
      checks: [
        { m: '!', c: v('amb'), t: '1 claim flagged: \u201c3 slots a day\u201d cadence stat needs a source' }, { m: '✓', c: v('grn'), t: '2 statistics verified' }, { m: '✓', c: v('grn'), t: 'Thread length fits X limits' },
      ],
      srcN: 4, sources: ['SparkToro', 'X thread', 'First Round', 'Reddit r/B2B'],
    },
  ];

  const [items, setItems] = useState(initialItems);

  const handleApprove = (idx: number) => {
    // Simply remove the item for the mock action
    setItems(items.filter((_, i) => i !== idx));
  };

  const handleReject = (idx: number) => {
    setItems(items.filter((_, i) => i !== idx));
  };

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "16px", maxWidth: "920px" }}>
      <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
        <span style={{ fontSize: "13px", color: "var(--mut)" }}>
          {items.length} post{items.length === 1 ? '' : 's'} waiting — nothing publishes without your approval.
        </span>
        <div style={{ flex: 1 }}></div>
        <span style={{ fontSize: "11px", color: "var(--faint)", cursor: "pointer" }}>Approval history</span>
      </div>

      {items.map((a, i) => (
        <section key={i} style={{ background: "var(--card)", border: "1px solid var(--line)", borderRadius: "12px", boxShadow: "var(--shadow)" }}>
          
          {/* Card Header */}
          <div style={{ display: "flex", alignItems: "center", gap: "10px", padding: "13px 16px", borderBottom: "1px solid var(--line)" }}>
            <span style={{ fontSize: "10px", fontWeight: 700, width: "20px", height: "20px", borderRadius: "4px", display: "inline-flex", alignItems: "center", justifyContent: "center", background: a.pBg, color: a.pFg, flex: "none" }}>{a.p}</span>
            <div style={{ minWidth: 0, flex: 1 }}>
              <div style={{ fontSize: "13px", fontWeight: 600, lineHeight: 1.3 }}>{a.title}</div>
              <div style={{ fontSize: "11px", color: "var(--faint)", marginTop: "1px" }}>{a.meta}</div>
            </div>
            <span style={{ fontSize: "10.5px", fontWeight: 600, padding: "2px 8px", borderRadius: "9px", background: "var(--ambbg)", color: "var(--amb)", whiteSpace: "nowrap" }}>Needs approval</span>
          </div>

          {/* Card Details */}
          <div style={{ display: "flex", flexWrap: "wrap", gap: "16px", padding: "14px 16px" }}>
            
            {/* Post Preview Box */}
            <div style={{ flex: "1 1 340px", minWidth: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
              <div style={{ fontSize: "10.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".05em", color: "var(--faint)" }}>Post preview</div>
              <textarea
                value={a.body}
                onChange={(e) => {
                  const updated = [...items];
                  updated[i].body = e.target.value;
                  setItems(updated);
                }}
                style={{
                  background: "var(--card2)", border: "1px solid var(--line)", borderRadius: "9px",
                  padding: "13px 14px", fontSize: "12.5px", lineHeight: 1.6, color: "var(--text)",
                  width: "100%", height: "140px", resize: "vertical", outline: "none", font: "inherit"
                }}
              />
            </div>

            {/* Fact Check, Scores, Sources Column */}
            <div style={{ flex: "1 1 250px", minWidth: "230px", display: "flex", flexDirection: "column", gap: "12px" }}>
              
              {/* Quality Scores */}
              <div>
                <div style={{ fontSize: "10.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".05em", color: "var(--faint)", marginBottom: "7px" }}>Quality · {a.q}</div>
                <div style={{ display: "flex", flexDirection: "column", gap: "6px" }}>
                  {a.scores.map((s, idx) => (
                    <div key={idx} style={{ display: "flex", alignItems: "center", gap: "8px" }}>
                      <span style={{ fontSize: "11px", color: "var(--mut)", width: "72px" }}>{s.k}</span>
                      <div style={{ flex: 1, height: "5px", borderRadius: "3px", background: "var(--chip)", overflow: "hidden" }}>
                        <div style={{ height: "100%", borderRadius: "3px", background: s.c, width: `${s.pct}%` }}></div>
                      </div>
                      <span style={{ fontSize: "11px", fontFamily: "'IBM Plex Mono',monospace", color: "var(--mut)", width: "26px", textAlign: "right" }}>{s.v}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Fact Check Checks */}
              <div>
                <div style={{ fontSize: "10.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".05em", color: "var(--faint)", marginBottom: "7px" }}>Fact-check</div>
                <div style={{ display: "flex", flexDirection: "column", gap: "5px" }}>
                  {a.checks.map((c, idx) => (
                    <div key={idx} style={{ display: "flex", gap: "8px", fontSize: "11.5px", alignItems: "flex-start" }}>
                      <span style={{ color: c.c, flex: "none" }}>{c.m}</span>
                      <span style={{ color: "var(--mut)", lineHeight: 1.45 }}>{c.t}</span>
                    </div>
                  ))}
                </div>
              </div>

              {/* Sources Citation */}
              <div>
                <div style={{ fontSize: "10.5px", fontWeight: 600, textTransform: "uppercase", letterSpacing: ".05em", color: "var(--faint)", marginBottom: "7px" }}>Sources · {a.srcN}</div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: "6px" }}>
                  {a.sources.map((s, idx) => (
                    <a key={idx} href="#" onClick={(e) => e.preventDefault()} style={{ fontSize: "11px", padding: "3px 9px", borderRadius: "10px", background: "var(--chip)", color: "var(--acc)", textDecoration: "none", border: "1px solid var(--line)" }}>{s}</a>
                  ))}
                </div>
              </div>

            </div>

          </div>

          {/* Action Footer */}
          <div style={{ display: "flex", alignItems: "center", gap: "8px", padding: "12px 16px", borderTop: "1px solid var(--line)", flexWrap: "wrap" }}>
            <span style={{ fontSize: "11.5px", color: "var(--mut)" }}>Suggested slot: <span style={{ color: "var(--text)", fontFamily: "'IBM Plex Mono',monospace" }}>{a.when}</span></span>
            <div style={{ flex: 1 }}></div>
            <button onClick={() => handleReject(i)} style={{ font: "inherit", fontSize: "12px", padding: "7px 13px", borderRadius: "7px", border: "1px solid transparent", background: "transparent", color: "var(--red)", cursor: "pointer" }}>Reject</button>
            <button style={{ font: "inherit", fontSize: "12px", padding: "7px 13px", borderRadius: "7px", border: "1px solid var(--line2)", background: "transparent", color: "var(--mut)", cursor: "pointer" }}>Request changes</button>
            <button onClick={() => handleApprove(i)} style={{ font: "inherit", fontSize: "12px", fontWeight: 600, padding: "7px 16px", borderRadius: "7px", border: "none", background: "var(--grn)", color: "#06251a", cursor: "pointer" }}>Approve &amp; schedule</button>
          </div>

        </section>
      ))}
    </div>
  );
}
